BPF: Include missing nospec.h to avoid build error
Commit 74e19ef0ff8061ef55957c3a ("uaccess: Add speculation barrier to
copy_from_user()") defines a default barrier_nospec() and removes the
#ifdefs in kernel/bpf/core.c, but doesn't include nospec.h, which causes
such a build error:

  CC      kernel/bpf/core.o
kernel/bpf/core.c: In function ‘___bpf_prog_run’:
kernel/bpf/core.c:1913:3: error: implicit declaration of function ‘barrier_nospec’; did you mean ‘barrier_data’? [-Werror=implicit-function-declaration]
   barrier_nospec();
   ^~~~~~~~~~~~~~
   barrier_data
cc1: some warnings being treated as errors

So include nospec.h to avoid the build error.

Fixes: 74e19ef0ff8061ef55957c3a ("uaccess: Add speculation barrier to copy_from_user()")
Signed-off-by: Huacai Chen <chenhuacai@loongson.cn>