selftests/bpf: fix getpeername/getsockname 32-bit compile errors
Sources for get(peer|sock)name(4|6)_prog.c include a "<string.h>" which
conflicts with a typedef in "vmlinux.h" when compiled for 32-bit systems:

In file included from /usr/include/string.h:33:
In file included from /usr/lib/llvm-18/lib/clang/18/include/stddef.h:77:
/usr/lib/llvm-18/lib/clang/18/include/__stddef_size_t.h:18:23: error: typedef redefinition with different types ('unsigned long' vs '__kernel_size_t' (aka 'unsigned int'))
   18 | typedef __SIZE_TYPE__ size_t;
      |                       ^
.../tools/testing/selftests/bpf/tools/include/vmlinux.h:20705:25: note: previous definition is here
20705 | typedef __kernel_size_t size_t;
      |                         ^
1 error generated.

The conflicts arise because "vmlinux.h" reflects the 32-bit host kernel,
while "<string.h>" reflects the 64-bit BPF VM. Fix this by dropping the
latter includes since they are unneeded anyway.

Fixes: bc467e953e4f ("selftests/bpf: Expand getsockname and getpeername tests")
Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>