samples: bpf: fix the compiling error
When compiling, the following error will appear.

"
samples/bpf//xdpsock_user.c:27:10: fatal error: sys/capability.h:
 No such file or directory
"
Now capability.h is in linux directory.

Fixes: 3627d9702d78 ("samples/bpf: Sample application for eBPF load and socket creation split")
Signed-off-by: Zhu Yanjun <zyjzyj2000@gmail.com>