bpf: Add BPF_KFUNC macro for defining kfuncs
kfuncs are functions defined in the kernel, which may be invoked by BPF
programs. They may or may not also be used as regular kernel functions,
implying that they may be static (in which case the compiler could e.g.
inline it away), or it could have external linkage, but potentially be
elided in an LTO build if a function is observed to never be used, and
is stripped from the final kernel binary.

We therefore require some convenience macro that kfunc developers can
use when defining a kfunc, and which will prevent all of the above
issues from happening. This is in contrast with what we have today,
where some kfunc definitions have "noinline", some have "__used", and
others are static and have neither.

In addition to providing the obvious correctness benefits, having such a
macro also provides an easy way to query for if kfuncs, as Christoph
suggested at the kernel maintainers summit
(https://lwn.net/Articles/908464/). This is currently possible by
grepping for BTF_ID_FLAGS(func, but having something more self
describing is useful.

Note that checkpatch complains about this patch with the following:

ERROR: Macros with multiple statements should be enclosed in a do - while loop
+#define BPF_KFUNC(proto)       \
+       proto;                  \
+       __used noinline proto

Given that we're wrapping the function definition and also including its
prototype, using do { } while(0) isn't an option. Hopefully it's
therefore inappropriate to ignore the warning.

Signed-off-by: David Vernet <void@manifault.com>