selftests/bpf: Fix compile if renameat2() support missing in libc
Test test_bpffs.c uses renameat2(), a syscall added in kernel 3.15 and
supported by glibc as a Linux-only extension, but unsupported by musl libc.
Update code to provide a stub definition if missing from libc, and avoid
compile errors like:

  test_bpffs.c: In function 'fn':
  test_bpffs.c:101:15: error: implicit declaration of function 'renameat2'; did you mean 'renameat'? [-Werror=implicit-function-declaration]
    101 |         err = renameat2(0, TDIR "/fs1/a", 0, TDIR "/fs1/b", RENAME_EXCHANGE);
        |               ^~~~~~~~~
        |               renameat
  test_bpffs.c:101:61: error: 'RENAME_EXCHANGE' undeclared (first use in this function)
    101 |         err = renameat2(0, TDIR "/fs1/a", 0, TDIR "/fs1/b", RENAME_EXCHANGE);
        |                                                             ^~~~~~~~~~~~~~~
  test_bpffs.c:101:61: note: each undeclared identifier is reported only once for each function it appears in
  test_bpffs.c:130:61: error: 'RENAME_NOREPLACE' undeclared (first use in this function)
    130 |         err = renameat2(0, TDIR "/fs1/b", 0, TDIR "/fs1/a", RENAME_NOREPLACE);
        |                                                             ^~~~~~~~~~~~~~~~
  cc1: all warnings being treated as errors

Fixes: 7e5ad817ec29 ("selftests/bpf: Test RENAME_EXCHANGE and RENAME_NOREPLACE on bpffs")
Signed-off-by: Tony Ambardar <Tony.Ambardar@gmail.com>