selftests/bpf: fix build with new LLVM
The progs/stream.c BPF program now uses arena helpers, so it includes
bpf_arena_common.h, which conflicts with the declarations generated
in vmlinux.h. This leads to the following build errors with the recent
LLVM:

    In file included from progs/stream.c:8:
    .../tools/testing/selftests/bpf/bpf_arena_common.h:47:15: error: conflicting types for 'bpf_arena_alloc_pages'
       47 | void __arena* bpf_arena_alloc_pages(void *map, void __arena *addr, __u32 page_cnt,
          |               ^
    .../tools/testing/selftests/bpf/tools/include/vmlinux.h:229284:14: note: previous declaration is here
     229284 | extern void *bpf_arena_alloc_pages(void *p__map, void *addr__ign, u32 page_cnt, int node_id, u64 flags) __weak __ksym;
            |              ^

    ... etc

Fix this by analogy with the 6a8260147745 ("bpf: selftests: Do not
use generated kfunc prototypes for arena progs") commit by adding the
BPF_NO_KFUNC_PROTOTYPES. As the test uses other kfuncs, declare them
specifically.

Fixes: 86f2225065be ("selftests/bpf: Add tests for arena fault reporting")
Signed-off-by: Anton Protopopov <a.s.protopopov@gmail.com>