ipmr: Don't mark ip6mr_rtnl_msg_handlers as __initconst
This gets referenced by the ip6_mr_cleanup function, so it must not be
discarded early:

WARNING: modpost: vmlinux: section mismatch in reference: ip6_mr_cleanup+0x14 (section: .exit.text) -> ip6mr_rtnl_msg_handlers (section: .init.rodata)
ERROR: modpost: Section mismatches detected.
Set CONFIG_SECTION_MISMATCH_WARN_ONLY=y to allow them.

Fixes: 3ac84e31b33e ("ipmr: Use rtnl_register_many().")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: NipaLocal <nipa@local>