libbpf: Use (uintptr_t) for a u64 cast to a void pointer to fix build on 32-bit arches
Noticed on several perf container builds:

  perfbuilder@number:~$ grep -B1 -A2 "cast to pointer"  dm.log/*\:*
  dm.log/ubuntu:18.04-x-arm-libbpf.c: In function 'bpf_object__create_maps':
  dm.log/ubuntu:18.04-x-arm:libbpf.c:5355:24: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  dm.log/ubuntu:18.04-x-arm-     map->mmaped = mmap((void *)map->map_extra, bpf_map_mmap_sz(map),
  dm.log/ubuntu:18.04-x-arm-                        ^
  --
  dm.log/ubuntu:18.04-x-powerpc-libbpf.c: In function 'bpf_object__create_maps':
  dm.log/ubuntu:18.04-x-powerpc:libbpf.c:5355:24: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  dm.log/ubuntu:18.04-x-powerpc-     map->mmaped = mmap((void *)map->map_extra, bpf_map_mmap_sz(map),
  dm.log/ubuntu:18.04-x-powerpc-                        ^
  --
  dm.log/ubuntu:18.04-x-sh4-libbpf.c: In function 'bpf_object__create_maps':
  dm.log/ubuntu:18.04-x-sh4:libbpf.c:5355:24: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  dm.log/ubuntu:18.04-x-sh4-     map->mmaped = mmap((void *)map->map_extra, bpf_map_mmap_sz(map),
  dm.log/ubuntu:18.04-x-sh4-                        ^
  perfbuilder@number:~$

I think Namhyung mentioned as well on a chat conversation about noticing
this on a 32-bit build on Debian.

Fixes: 79ff13e99169ddb0 ("libbpf: Add support for bpf_arena.")
Reported-by: Namhyung Kim <namhyung@kernel.org>
Cc: Alexei Starovoitov <ast@kernel.org>
Cc: Andrii Nakryiko <andrii@kernel.org>
Cc: Ian Rogers <irogers@google.com>
Signed-off-by: Arnaldo Carvalho de Melo <acme@redhat.com>