selftests/bpf: fix 32-bit compile errors in net_timestamping.c, type_cast.c
Current code determines 'struct skb_shared_info' from 'struct sk_buff' by
emulating the macro skb_shinfo(skb), but only the 64-bit implementation.
Since 'struct sk_buff' differs for 32-bit this leads to build errors:

  progs/type_cast.c:49:41: error: invalid operands to binary expression ('unsigned char *' and 'sk_buff_data_t' (aka 'unsigned char *'))
     49 |         shared_info = bpf_core_cast(kskb->head + kskb->end, struct skb_shared_info);
        |                                     ~~~~~~~~~~ ^ ~~~~~~~~~
  .../tools/include/bpf/bpf_core_read.h:338:36: note: expanded from macro 'bpf_core_cast'
    338 |         ((typeof(type) *)bpf_rdonly_cast((ptr), bpf_core_type_id_kernel(type)))
        |                                           ^~~
  1 error generated.

and

  progs/net_timestamping.c:134:35: error: invalid operands to binary expression ('unsigned char *' and 'sk_buff_data_t' (aka 'unsigned char *'))
    134 |         shinfo = bpf_core_cast(skb->head + skb->end, struct skb_shared_info);
        |                                ~~~~~~~~~ ^ ~~~~~~~~
  .../tools/include/bpf/bpf_core_read.h:338:36: note: expanded from macro 'bpf_core_cast'
    338 |         ((typeof(type) *)bpf_rdonly_cast((ptr), bpf_core_type_id_kernel(type)))
        |                                           ^~~
  1 error generated.

Fix by using the new skb_end_pointer() BPF macro instead of hard-coding the
pointer arithmetic.

Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>