bpf: avoid padding in struct bpf_common_attr
Building linux/bpf.h with -Wpadded shows an unintentionally
added portion of padding because of the 64-bit alignment:

./usr/include/linux/bpf.h:1510:1: error: padding struct size to alignment boundary with 4 bytes [-Werror=padded]

Avoid this by adding explicit padding.

Fixes: f28771c0691b ("bpf: Extend BPF syscall with common attributes support")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>