samples/bpf: Fix xdpsock with '-M' parameter missing unload process
Execute the following command and exit, then execute it again, the
following error will be reported.

$ sudo ./samples/bpf/xdpsock -i ens4f2 -M
^C
$ sudo ./samples/bpf/xdpsock -i ens4f2 -M
libbpf: elf: skipping unrecognized data section(16) .eh_frame
libbpf: elf: skipping relo section(17) .rel.eh_frame for section(16) .eh_frame
libbpf: Kernel error message: XDP program already attached
ERROR: link set xdp fd failed

commit c9d27c9e8dc7 ("samples: bpf: Do not unload prog within xdpsock")
removed the unload prog code because of the presence of bpf_link. This
is fine if XDP_SHARED_UMEM is disable, but if it is enable, unload prog
is still needed.

Fixes: c9d27c9e8dc7 ("samples: bpf: Do not unload prog within xdpsock")
Signed-off-by: Wang Hai <wanghai38@huawei.com>
Acked-by: Magnus Karlsson <magnus.karlsson@intel.com>