btf: Fix error of Macros with multiple statements
This patch fixes an error reported by checkpatch.pl

ERROR: Macros with multiple statements should be
enclosed in a do while loop

To fix this a do while(0) loop is used
to encloses the multiple statements.

Signed-off-by: Jules Irenge <jbi.octave@gmail.com>