bpf: Include missing nospec.h to avoid build error.
Commit 74e19ef0ff80 ("uaccess: Add speculation barrier to copy_from_user()")
defines a default barrier_nospec() and removes the
such a build error:

  CC      kernel/bpf/core.o
kernel/bpf/core.c: In function ‘___bpf_prog_run’:
kernel/bpf/core.c:1913:3: error: implicit declaration of function ‘barrier_nospec’; did you mean ‘barrier_data’? [-Werror=implicit-function-declaration]
   barrier_nospec();
   ^~~~~~~~~~~~~~
   barrier_data
cc1: some warnings being treated as errors

So include nospec.h to avoid the build error.

Fixes: 74e19ef0ff80 ("uaccess: Add speculation barrier to copy_from_user()")
Signed-off-by: Huacai Chen <chenhuacai@loongson.cn>
Link: https://lore.kernel.org/r/20230222025048.3677315-1-chenhuacai@loongson.cn
Signed-off-by: Alexei Starovoitov <ast@kernel.org>