selftests/bpf: fix the compilation errors caused by larchintrin.h
On the LoongArch platform, the header file 'larchintrin.h' is provided by
the package clang-libs, and it is necessary to add CLANG_SYS_INCLUDES to
the compilation command.

make M=samples/bpf, compilation errors:

In file included from sockex2_kern.c:2:
In file included from /root/work/src/github/linux/include/uapi/linux/in.h:25:
In file included from /root/work/src/github/linux/include/linux/socket.h:8:
In file included from /root/work/src/github/linux/include/linux/uio.h:9:
In file included from /root/work/src/github/linux/include/linux/thread_info.h:60:
In file included from /root/work/src/github/linux/arch/loongarch/include/asm/thread_info.h:15:
In file included from /root/work/src/github/linux/arch/loongarch/include/asm/processor.h:13:
In file included from /root/work/src/github/linux/arch/loongarch/include/asm/cpu-info.h:11:
/root/work/src/github/linux/arch/loongarch/include/asm/loongarch.h:13:10: fatal error: 'larchintrin.h' file not found
   13 | #include <larchintrin.h>

Signed-off-by: zhangxi <zhangxi@kylinos.cn>