selftests/bpf: fix uprobe_syscall.c 32-bit compile error
The source includes a "<string.h>" which conflicts with a typedef in
"vmlinux.h" when compiled for 32-bit systems:

In file included from /usr/include/string.h:33:
In file included from /usr/lib/llvm-18/lib/clang/18/include/stddef.h:77:
/usr/lib/llvm-18/lib/clang/18/include/__stddef_size_t.h:18:23: error: typedef redefinition with different types ('unsigned long' vs '__kernel_size_t' (aka 'unsigned int'))
   18 | typedef __SIZE_TYPE__ size_t;
      |                       ^
.../tools/testing/selftests/bpf/tools/include/vmlinux.h:20705:25: note: previous definition is here
20705 | typedef __kernel_size_t size_t;
      |                         ^
1 error generated.

The conflict arises because "vmlinux.h" reflects the 32-bit host kernel,
while "<string.h>" reflects the 64-bit BPF VM. Fix this by dropping the
latter include since they are unneeded anyway.

Fixes: 3e8e25761a40 ("selftests/bpf: Add uretprobe syscall test for regs integrity")
Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>