uapi: Add missing linux/stddef.h header file to in.h
commit 5854a09b4957 ("net/ipv4: Use __DECLARE_FLEX_ARRAY() helper") does
not include "linux/stddef.h" header file, and tools headers update
linux/in.h copy, BPF prog fails to be compiled:

    CLNG-BPF [test_maps] bpf_flow.bpf.o
    CLNG-BPF [test_maps] cgroup_skb_sk_lookup_kern.bpf.o
  In file included from progs/cgroup_skb_sk_lookup_kern.c:9:
  /root/linux/tools/include/uapi/linux/in.h:199:3: error: type name requires a specifier or qualifier
                  __DECLARE_FLEX_ARRAY(__be32, imsf_slist_flex);
                  ^
  /root/linux/tools/include/uapi/linux/in.h:199:32: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
                  __DECLARE_FLEX_ARRAY(__be32, imsf_slist_flex);
                                               ^
  2 errors generated.

To maintain consistency, add missing header file to kernel.

Fixes: 5854a09b4957 ("net/ipv4: Use __DECLARE_FLEX_ARRAY() helper")
Signed-off-by: Yang Jihong <yangjihong1@huawei.com>