pinctrl: ambarella: add CONFIG_OF dependency
On randconfig builds without CONFIG_OF, this driver fails to link:

x86_64-linux-ld: vmlinux.o: in function `pinconf_generic_dt_node_to_map_all':
pinctrl-ambarella.c:(.text+0x54cdf0): undefined reference to `pinconf_generic_dt_node_to_map'

Enforce OF as a dependency as we do for other such drivers.

Fixes: b40e9d140c24 ("pinctrl: ambarella: add CV75 pin controller")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Linus Walleij <linusw@kernel.org>