tools/bpf: Add missing fclose.
Cppcheck find a error as below:
	bpf_dbg.c:1397:2: error: Resource leak: fin [resourceLeak]
Add fclose to rm this error.

Signed-off-by: zhang jiao <zhangjiao2@cmss.chinamobile.com>