Documentation/gpu: fix location of drm_panel kernel-doc
The source file location was changed, so update the documentation
accordingly. Fixes these warnings:

ERROR: Cannot find file ../drivers/gpu/drm/bridge/panel.c
ERROR: Cannot find file ../drivers/gpu/drm/bridge/panel.c
WARNING: No kernel-doc for file ../drivers/gpu/drm/bridge/panel.c

Fixes: aa8a8c7e4641 ("drm/bridge: panel: move all code to drm_panel.c")
Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Reviewed-by: Luca Ceresoli <luca.ceresoli@bootlin.com>
Link: https://patch.msgid.link/20260928210326.1526997-1-rdunlap@infradead.org
Signed-off-by: Luca Ceresoli <luca.ceresoli@bootlin.com>