selftests/bpf: fix compiling trace_helpers.c for 32-bit
The code assumes 64-bit usage and fails to build targeting 32-bit systems:

trace_helpers.c: In function 'procmap_query':
trace_helpers.c:261:24: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  261 |         q.query_addr = (__u64)addr;
      |                        ^
trace_helpers.c:262:27: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  262 |         q.vma_name_addr = (__u64)path_buf;
      |                           ^
trace_helpers.c:264:27: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
  264 |         q.build_id_addr = (__u64)build_id_buf;
      |                           ^
cc1: all warnings being treated as errors

Fix by adding an intermediate (uintptr_t) cast.

Fixes: 4e9e07603ecd ("selftests/bpf: make use of PROCMAP_QUERY ioctl if available")
Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>