selftests/bpf: Suppress int-to-pointer warning on 32-bit arm
After previous change to struct pt_regs casting/sizing in bpf_tracing.h,
we now see several compile warnings related to casting:

    error: cast to 'void *' from smaller integer type 'unsigned int'

Update Makefile to silence the error building BPF progs for arm 32-bit.

Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>