selftests/bpf: Fix printf output directive in xdp_hw_metadata.c
Use the explicit 64-bit output directive '%llx' to avoid compile errors due
to possible integer truncation, seen with GCC 12.3 targeting 32-bit ARM:

xdp_hw_metadata.c: In function ‘open_xsk’:
xdp_hw_metadata.c:138:46: error: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘u64’ {aka ‘long long unsigned int’} [-Werror=format=]
  138 |                 printf("%p: tx_desc[%d] -> %lx\n", xsk, i, addr);
      |                                            ~~^             ~~~~
      |                                              |             |
      |                                              |             u64 {aka long long unsigned int}
      |                                              long unsigned int
      |                                            %llx
xdp_hw_metadata.c:146:46: error: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘u64’ {aka ‘long long unsigned int’} [-Werror=format=]
  146 |                 printf("%p: rx_desc[%d] -> %lx\n", xsk, i, addr);
      |                                            ~~^             ~~~~
      |                                              |             |
      |                                              |             u64 {aka long long unsigned int}
      |                                              long unsigned int
      |                                            %llx

Fixes: 297a3f124155 ("selftests/bpf: Simple program to dump XDP RX metadata")
Signed-off-by: Tony Ambardar <tony.ambardar@gmail.com>