bpf: fix bpf compile error caused by CONFIG_CGROUP_BPF
We failed to compile when CONFIG_BPF_LSM is enabled but CONFIG_CGROUP_BPF
is not set. The failings are shown as below:

kernel/bpf/trampoline.o: in function `bpf_trampoline_link_cgroup_shim'
trampoline.c: undefined reference to `bpf_cgroup_atype_get'
kernel/bpf/bpf_lsm.o: In function `bpf_lsm_find_cgroup_shim':
bpf_lsm.c: undefined reference to `__cgroup_bpf_run_lsm_current'
bpf_lsm.c: undefined reference to `__cgroup_bpf_run_lsm_sock'
bpf_lsm.c: undefined reference to `__cgroup_bpf_run_lsm_socket'

Fix them by protecting these functions with CONFIG_CGROUP_BPF.

Fixes: 69fd337a975c ("bpf: per-cgroup lsm flavor")
Signed-off-by: Xu Jia <xujia39@huawei.com>