perf llvm: Fix compile bpf failed to cope with latest llvm
Inline assembly used by asm/sysreg.h is incompatible with latest llvm,
If bpf C program include "linux/ptrace.h" (which is common), compile will fail:

 # perf --debug verbose record -e bpf-output/no-inherit,name=evt/ \
                              -e ./perf_bpf_test.c/map:channel.event=evt/ ls
 [SNIP]
 /lib/modules/5.17/build/./arch/x86/include/asm/arch_hweight.h:20:7: error: invalid output constraint '=a' in asm
                          : "="REG_OUT (res)
                           ^
 /lib/modules/5.17/build/./arch/x86/include/asm/arch_hweight.h:48:7: error: invalid output constraint '=a' in asm
                          : "="REG_OUT (res)
                           ^
 In file included from /root/projects/perf-bpf/perf_bpf_test.c:2:
 In file included from /lib/modules/5.17/build/./include/linux/ptrace.h:6:
 In file included from /lib/modules/5.17/build/./include/linux/sched.h:12:
 In file included from /lib/modules/5.17/build/./arch/x86/include/asm/current.h:6:
 In file included from /lib/modules/5.17/build/./arch/x86/include/asm/percpu.h:27:
 In file included from /lib/modules/5.17/build/./include/linux/kernel.h:25:
 In file included from /lib/modules/5.17/build/./include/linux/math.h:6:
 /lib/modules/5.17.0/build/./arch/x86/include/asm/div64.h:85:28: error: invalid output constraint '=a' in asm
         asm ("mulq %2; divq %3" : "=a" (q)
 [SNIP]
 # cat /root/projects/perf-bpf/perf_bpf_test.c
 /************************ BEGIN **************************/
 #include <uapi/linux/bpf.h>
 #include <linux/ptrace.h>
 #include <linux/types.h>
 #define SEC(NAME) __attribute__((section(NAME), used))

 struct bpf_map_def {
         unsigned int type;
         unsigned int key_size;
         unsigned int value_size;
         unsigned int max_entries;
 };

 static int (*perf_event_output)(void *, struct bpf_map_def *, int, void *,
     unsigned long) = (void *)BPF_FUNC_perf_event_output;

 struct bpf_map_def SEC("maps") channel = {
         .type = BPF_MAP_TYPE_PERF_EVENT_ARRAY,
         .key_size = sizeof(int),
         .value_size = sizeof(__u32),
         .max_entries = __NR_CPUS__,
 };

 #define MIN_BYTES 1024

 SEC("func=vfs_read")
 int bpf_myprog(struct pt_regs *ctx)
 {
         long bytes = ctx->dx;
         if (bytes >= MIN_BYTES) {
                 perf_event_output(ctx, &channel, BPF_F_CURRENT_CPU,
                                   &bytes, sizeof(bytes));
         }

         return 0;
 }

char _license[] SEC("license") = "GPL";
int _version SEC("version") = LINUX_VERSION_CODE;
/************************* END ***************************/

Compilation command is modified to be the same as that in samples/bpf/Makefile,
use clang | opt | llvm-dis | llc chain of commands to solve the problem.
see the comment in samples/bpf/Makefile.

Modifications:
1. Change "clang --target bpf" to chain of commands "clang | opt | llvm-dis | llc"
2. Delete "CLANG_EMIT_LLVM" and "LLVM_OPTIONS_PIPE" macros from the compilation
   command because the two macros are not defined and the content is empty.
3. Add options llvm.llvm-opt-path, llvm.llvm-dis-path, and llvm.llc-path to
   perf config for user-defined settings, which are similar to llvm.clang-path.
4. Add "-Wno-address-of-packed-member" to resolve the compilation warning of
   "/lib/modules/5.17/build/./arch/x86/include/asm/processor.h:552:17: \
    warning: taking address of packed member 'sp0' of class or structure \
    'x86_hw_tss' may result in an unaligned pointer value [-Waddress-of-packed-member]
        this_cpu_write(cpu_tss_rw.x86_tss.sp0, sp0);
                       ^~~~~~~~~~~~~~~~~~~~~~
   /lib/modules/5.17/build/./include/linux/percpu-defs.h:508:68: note: \
   expanded from macro 'this_cpu_write' \
    #define this_cpu_write(pcp, val)        __pcpu_size_call(this_cpu_write_, pcp, val)",
   which is similar to that of sample/bpf/Makefile.

Signed-off-by: Yang Jihong <yangjihong1@huawei.com>