bpf: Fix libbpf_version.h build dependency.
Auto generated libbpf_version.h could be causing build issue like:
$ make
CC [U]  kernel/bpf/preload/iterators/iterators.o
In file included from ../tools/lib/bpf/libbpf.h:20,
                 from ../kernel/bpf/preload/iterators/iterators.c:10:
../tools/lib/bpf/libbpf_common.h:13:10: fatal error: libbpf_version.h: No such file or directory
   13 | #include "libbpf_version.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [../scripts/Makefile.userprogs:43: kernel/bpf/preload/iterators/iterators.o] Error 1

Fix it by force rebuilding libbpf.

Fixes: 0b46b7550560 ("libbpf: Add LIBBPF_DEPRECATED_SINCE macro for scheduling API deprecations")
Suggested-by: Andrii Nakryiko <andrii@kernel.org>
Signed-off-by: Alexei Starovoitov <ast@kernel.org>